//@version=6
indicator("Array OOB Tests")
a = array.from(1, 2, 3)
bad = array.get(a, 5)
bad2 = array.get(a, array.size(a))
good = array.get(a, 2)
good2 = array.get(a, array.size(a) - 1)
good3 = array.get(a, -1)
bad3 = array.get(a, -4)
b = array.new<float>(0)
bad4 = b.first()
if b.size() > 0
    good4 = b.first()
for i = 0 to 10
    v = array.get(a, i)
for i = 0 to array.size(a) - 1
    v2 = array.get(a, i)
